on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-test:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: |-
          astralox/multi-client-k8s-gh
          astralox/multi-server-k8s-gh
          astralox/multi-worker-k8s-gh

    - name: Build and push Docker image
      id: pushclient
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Docker image
      id: pushserver
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Docker image
      id: pushworker
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./worker
        file: ./worker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: azure/setup-kubectl@v4
      
      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v4
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: multi-k8s-dal
          resource-group: multi-k8s-dal
      
      - uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
            k8s
          images: |-
            hub.docker.com/astralox/multi-client:${{ github.sha }}
            hub.docker.com/astralox/multi-server:${{ github.sha }}
            hub.docker.com/astralox/multi-worker:${{ github.sha }}
